.PHONY: build run db-up db-down db-migrate db-migrate-down test clean

DB_DSN="postgres://gatekeeper:cookies@localhost:5432/gatekeeper?sslmode=disable"

build:
	go build -o ./bin/api ./cmd/api

run:
	go run ./cmd/api -db-dsn=$(DB_DSN)

db-migrate:
	migrate -path ./migrations -database $(DB_DSN) up

db-migrate-down:
	migrate -path ./migrations -database $(DB_DSN) down 1

test:
	go test -v ./...

clean:
	rm -rf ./bin ./uploads
